plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.sentry.gradle)
}

def isFirebase = rootProject.file('app/google-services.json').exists()
if (isFirebase) {
    println("exists google-services.json")
    apply plugin: 'com.google.gms.google-services'
}

android {
    namespace 'me.liaoheng.wallpaper'
    compileSdkVersion libs.versions.compileSdkVersion.get() as int

    defaultConfig {
        minSdkVersion libs.versions.minSdkVersion.get() as int
        targetSdkVersion libs.versions.targetSdkVersion.get() as int
        applicationId "me.liaoheng.wallpaper"
        versionCode 1
        versionName "1"
    }

    def isSigning = true
    signingConfigs {
        config {
            try {
                keyAlias project.findProperty('KEY_ALIAS') ?: System.getenv('KEY_ALIAS') ?: ""
                keyPassword project.findProperty('KEY_PASSWORD') ?: System.getenv('KEY_PASSWORD') ?: ""
                storeFile file(project.findProperty('STORE_FILE') ?: System.getenv('STORE_FILE') ?: "")
                storePassword project.findProperty('STORE_PASSWORD') ?: System.getenv('STORE_PASSWORD') ?: ""
                if (keyAlias.isEmpty()) {
                    throw new GradleException("keyAlias is empty")
                }
            } catch (Exception ignored) {
                isSigning = false
                printf("not signingConfigs")
            }
        }
    }
    //https://github.com/getsentry/sentry-android-gradle-plugin/issues/782
    buildTypes {
        release {
            def sentryDsn = project.findProperty('SENTRY_DSN') ?: System.getenv('SENTRY_DSN') ?: ""
            addManifestPlaceholders([sentryDsn: sentryDsn])
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (isSigning) signingConfig signingConfigs.config
        }
        debug {
            addManifestPlaceholders([sentryDsn: ""])
        }
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    android.applicationVariants.configureEach { variant ->
        if (variant.buildType.name == 'release') {
            variant.outputs.configureEach {
                outputFileName = "StarthBingWallpaper-${variant.versionName}.apk"
            }
        }
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
    lint {
        abortOnError false
        disable 'ExtraTranslation'
    }
}

dependencies {
    testImplementation libs.robolectric
    testImplementation libs.junit
    testImplementation libs.joda.time
    //android system
    implementation libs.androidx.core.ktx
    implementation libs.androidx.annotation
    implementation libs.google.material
    implementation libs.androidx.palette
    implementation libs.androidx.browser
    implementation(libs.androidx.preference) {
        exclude group: 'androidx.lifecycle', module: 'lifecycle-viewmodel-ktx'
    }
    implementation libs.androidx.swiperefreshlayout

    implementation libs.androidx.work.runtime
    implementation libs.androidx.datastore.preferences
    implementation libs.androidx.datastore.preferences.rxjava3
    implementation libs.androidx.datastore.preferences.proto
    compileOnly libs.kotlinx.coroutines.rx3
    if (isFirebase) {
        implementation(libs.google.firebase) {
            exclude module: "play-services-ads-identifier"
        }
    } else {
        printf("not exists google-services.json")
        compileOnly libs.google.firebase
    }

    implementation libs.sentry.android.core

    implementation libs.joda.time.android
    implementation libs.google.guava
    implementation libs.google.gson
    implementation libs.glide
    annotationProcessor libs.glide.compiler
    implementation libs.glide.okhttp3.integration
    implementation libs.okhttp
    implementation libs.okhttp.logging
    implementation libs.okhttp.doh
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.retrofit.adapter.rxjava3
    implementation libs.rxandroid3
    implementation libs.rxjava3
    implementation libs.rxlifecycle4
    implementation libs.rxlifecycle4.android

    //https://github.com/Commit451/NativeStackBlur
    implementation libs.native.stack.blur

    //https://github.com/scottyab/rootbeer
    implementation libs.rootbeer

    //https://github.com/Clans/FloatingActionButton
    implementation libs.fab

    //https://github.com/apl-devs/AppIntro
    implementation libs.app.intro

    //https://github.com/davemorrissey/subsampling-scale-image-view
    implementation libs.subsampling.scale.image.view

    //    implementation group: "com.github.liaoheng", name: "common-core", version: "0.1.1-SNAPSHOT", changing: true
    //    implementation group: "com.github.liaoheng", name: "common-adapter", version: "0.1.1-SNAPSHOT", changing: true
    implementation libs.common.core
    implementation libs.common.adapter
}
//configurations.all {
//    // check for updates every build
//    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
//}